### ISSUE TITLE
Bug Report / Help Request

### ISSUE THREAD

**Issue by Weark** [titivermeesch/CommandTimer#17] opened 2019-06-07 07:53 UTC
I am having problems in the menu when using: /commandtimer
See: https://paste.ubuntu.com/p/9qWspfrTYw/

Could you do the configuration of 3 commands for me and send me the config here?

1 °
- Console
- Execulate:
'rg flag arena entry allow'
'say Open arena'
- Only every Saturday at 00:00

2 °
- Console
- Execultar: rg flag arena entry deny
'say Arena closed'
- Only every Monday at 00:00

3 °
- Console
- Execulate: giveall 322: 1 1
- Have a 50% chance of being executed.
- Every day at 15:00

This will help me a lot, thank you.

**Comment by titivermeesch** [comment] 2019-06-07 11:21
This is a know issue in the latest version and I'm working on a fix for that, you can use an older version.

**Comment by Weark** [comment] 2019-06-08 02:00
I tried using the older version but it did not work since I am using PaperSpigot 1.8.8 and the plugin version has no compatibility.

Could you make config.yml for me and send me to use it in the latest version?
I just need those 3.

Thank you for your support.

**Comment by titivermeesch** [comment] 2019-06-08 07:23
The problem is with paperspigot, there are some compatibility issues with that fork.
It's not a config issue. I'll to fix it today

**Comment by titivermeesch** [comment] 2019-06-08 07:57
`timeonload: true
settings:
    tasks:
        '1':
            commands:
                - rg flag arena entry allow
                - say Open arena
            onhour: true
            onday: true
            time: '00:00'
            days:
                - 'SATURDAY'
            gender: console
        '1':
            commands:
                - rg flag arena entry deny
                - say Arena closed
            onhour: true
            onday: true
            time: '00:00'
            days:
                - 'MONDAY'
            gender: console
        '3':
            gender: console
            commands:
                - giveall 322:1 1
            onhour: true
            onday: true
            useRandom: true
            random: 0.5
            time: '15:00'
            days:
              - 'MONDAY'
              - 'TUESDAY'
              - 'WEDNESDAY'
              - 'THURSDAY'
              - 'FRIDAY'
              - 'SATURDAY'
              - 'SUNDAY'
`

Here is the config,
Bug should be fixed in latest version

**Closed by titivermeesch** 2019-06-08 07:57 UTC
